/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "百香果的前端进阶",
  "description": "百香果的文档, vuepress 文档",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/apple-touch-icon.png"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#ffffff"
      }
    ],
    [
      "meta",
      {
        "name": "google-site-verification",
        "content": "Ld_AEWr30siza2LmmZ12csitRGsSj9gqqEAch0UXkTc"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/apple-touch-icon-152x152.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "百香果的前端进阶",
        "tagline": "文档, 博客",
        "actionText": "进入笔记 →",
        "actionLink": "/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4ea1e318",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "关于~~文档~~笔记",
          "slug": "关于文档笔记"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午12点49分"
    },
    {
      "title": "数据写入",
      "frontmatter": {
        "title": "数据写入"
      },
      "regularPath": "/computer/data-write.html",
      "relativePath": "computer/data-write.md",
      "key": "v-0b15fbd8",
      "path": "/computer/data-write.html",
      "headers": [
        {
          "level": 2,
          "title": "机械硬盘",
          "slug": "机械硬盘"
        },
        {
          "level": 2,
          "title": "固态硬盘",
          "slug": "固态硬盘"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午1点52分"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-57c4d407",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "写文档的目的 ?",
          "slug": "写文档的目的"
        },
        {
          "level": 2,
          "title": "写文档的想法",
          "slug": "写文档的想法"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午3点11分"
    },
    {
      "title": "首页",
      "frontmatter": {
        "title": "首页"
      },
      "regularPath": "/computer/",
      "relativePath": "computer/README.md",
      "key": "v-85028392",
      "path": "/computer/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午1点52分"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我"
      },
      "regularPath": "/guide/about-me.html",
      "relativePath": "guide/about-me.md",
      "key": "v-cd6e9620",
      "path": "/guide/about-me.html",
      "lastUpdated": "2020年7月19日星期日下午1点52分"
    },
    {
      "title": "文档风格",
      "frontmatter": {
        "title": "文档风格"
      },
      "regularPath": "/guide/docs-style.html",
      "relativePath": "guide/docs-style.md",
      "key": "v-256ecee2",
      "path": "/guide/docs-style.html",
      "headers": [
        {
          "level": 2,
          "title": "标点符号",
          "slug": "标点符号"
        },
        {
          "level": 3,
          "title": "1. 顿号",
          "slug": "_1-顿号"
        },
        {
          "level": 3,
          "title": "2. 分号",
          "slug": "_2-分号"
        },
        {
          "level": 3,
          "title": "3. 逗号",
          "slug": "_3-逗号"
        },
        {
          "level": 3,
          "title": "4. 句号",
          "slug": "_4-句号"
        },
        {
          "level": 3,
          "title": "5. 冒号",
          "slug": "_5-冒号"
        },
        {
          "level": 2,
          "title": "文档结构",
          "slug": "文档结构"
        },
        {
          "level": 3,
          "title": "1. 文档命名",
          "slug": "_1-文档命名"
        },
        {
          "level": 3,
          "title": "2. 文档标题",
          "slug": "_2-文档标题"
        },
        {
          "level": 2,
          "title": "文本规范",
          "slug": "文本规范"
        },
        {
          "level": 3,
          "title": "1. 行文风格",
          "slug": "_1-行文风格"
        },
        {
          "level": 3,
          "title": "2. 段落",
          "slug": "_2-段落"
        },
        {
          "level": 3,
          "title": "3. 语句",
          "slug": "_3-语句"
        },
        {
          "level": 3,
          "title": "4. 文本",
          "slug": "_4-文本"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午1点52分"
    },
    {
      "title": "网络是怎样连接的",
      "frontmatter": {
        "title": "网络是怎样连接的",
        "sidebarDepth": 2
      },
      "regularPath": "/computer/how-networks-work.html",
      "relativePath": "computer/how-networks-work.md",
      "key": "v-7fe20bb0",
      "path": "/computer/how-networks-work.html",
      "headers": [
        {
          "level": 2,
          "title": "第一章 浏览器生成消息 -- 探索浏览器内部",
          "slug": "第一章-浏览器生成消息-探索浏览器内部"
        },
        {
          "level": 3,
          "title": "1. 生成 HTTP 请求消息",
          "slug": "_1-生成-http-请求消息"
        },
        {
          "level": 3,
          "title": "2. 向 DNS 服务器查询 Web 服务器的 IP 地址",
          "slug": "_2-向-dns-服务器查询-web-服务器的-ip-地址"
        },
        {
          "level": 3,
          "title": "3. 全世界 DNS 服务器的大接力",
          "slug": "_3-全世界-dns-服务器的大接力"
        },
        {
          "level": 3,
          "title": "4. 委托协议栈发送消息",
          "slug": "_4-委托协议栈发送消息"
        },
        {
          "level": 2,
          "title": "第二章 用电信号传递 TCP/IP -- 探索协议栈和网卡",
          "slug": "第二章-用电信号传递-tcp-ip-探索协议栈和网卡"
        },
        {
          "level": 3,
          "title": "1. 创建套接字",
          "slug": "_1-创建套接字"
        },
        {
          "level": 3,
          "title": "2. 连接服务器",
          "slug": "_2-连接服务器"
        },
        {
          "level": 3,
          "title": "3. 收发数据",
          "slug": "_3-收发数据"
        },
        {
          "level": 3,
          "title": "4. 从服务器断开并删除套接字",
          "slug": "_4-从服务器断开并删除套接字"
        },
        {
          "level": 3,
          "title": "5. IP 与以太网的包收发操作",
          "slug": "_5-ip-与以太网的包收发操作"
        },
        {
          "level": 3,
          "title": "6. UDP 协议的收发操作",
          "slug": "_6-udp-协议的收发操作"
        },
        {
          "level": 2,
          "title": "第三章 从网络到网络设备 -- 搜索集线器、交换机和路由器",
          "slug": "第三章-从网络到网络设备-搜索集线器、交换机和路由器"
        },
        {
          "level": 3,
          "title": "1. 信号在网线和集线器中传输",
          "slug": "_1-信号在网线和集线器中传输"
        },
        {
          "level": 3,
          "title": "2. 交换机的包转发操作",
          "slug": "_2-交换机的包转发操作"
        },
        {
          "level": 3,
          "title": "3. 路由器的包转发操作",
          "slug": "_3-路由器的包转发操作"
        },
        {
          "level": 3,
          "title": "4. 路由器的附加功能",
          "slug": "_4-路由器的附加功能"
        },
        {
          "level": 2,
          "title": "第四章 通过接入网进入互联网内部 -- 探索接入网和网络运营商",
          "slug": "第四章-通过接入网进入互联网内部-探索接入网和网络运营商"
        },
        {
          "level": 3,
          "title": "1. ADSL 接入网的结构和工作方式",
          "slug": "_1-adsl-接入网的结构和工作方式"
        },
        {
          "level": 3,
          "title": "2. 光纤接入网（FTTH）",
          "slug": "_2-光纤接入网（ftth）"
        },
        {
          "level": 3,
          "title": "3. 接入网中使用的 PPP 和隧道",
          "slug": "_3-接入网中使用的-ppp-和隧道"
        },
        {
          "level": 3,
          "title": "4. 网络运营商的内部",
          "slug": "_4-网络运营商的内部"
        },
        {
          "level": 3,
          "title": "5. 跨越运营商的网络包",
          "slug": "_5-跨越运营商的网络包"
        },
        {
          "level": 2,
          "title": "第五章 服务器端的局域网有什么玄机",
          "slug": "第五章-服务器端的局域网有什么玄机"
        },
        {
          "level": 3,
          "title": "1. Web 服务器的部署地点",
          "slug": "_1-web-服务器的部署地点"
        },
        {
          "level": 3,
          "title": "2. 防火墙的结构和原理",
          "slug": "_2-防火墙的结构和原理"
        },
        {
          "level": 3,
          "title": "3. 通过请求平分给多台服务器来平衡负载",
          "slug": "_3-通过请求平分给多台服务器来平衡负载"
        },
        {
          "level": 3,
          "title": "4. 使用缓存服务器来分担负载",
          "slug": "_4-使用缓存服务器来分担负载"
        },
        {
          "level": 3,
          "title": "5. 内容分发服务",
          "slug": "_5-内容分发服务"
        },
        {
          "level": 2,
          "title": "第六章 请求到达 Web 服务器，响应返回浏览器 -- 短短几秒的 “漫长旅行” 迎来终点",
          "slug": "第六章-请求到达-web-服务器，响应返回浏览器-短短几秒的-漫长旅行-迎来终点"
        },
        {
          "level": 3,
          "title": "1. 服务器概览",
          "slug": "_1-服务器概览"
        },
        {
          "level": 3,
          "title": "2. 服务器的接收操作",
          "slug": "_2-服务器的接收操作"
        },
        {
          "level": 3,
          "title": "3. Web 服务器程序解释请求消息并作出响应",
          "slug": "_3-web-服务器程序解释请求消息并作出响应"
        },
        {
          "level": 3,
          "title": "4. 浏览器响应消息并显示内容",
          "slug": "_4-浏览器响应消息并显示内容"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午1点52分"
    }
  ],
  "themeConfig": {
    "lastUpdated": "上次更新",
    "repo": "TTTurbo/documents",
    "editLinks": true,
    "editLinkText": "编辑文档！",
    "docsDir": "docs",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "先导",
        "link": "/guide/"
      },
      {
        "text": "计算机",
        "link": "/computer/"
      },
      {
        "text": "系统",
        "items": [
          {
            "text": "Linux",
            "link": "/os/linux/"
          },
          {
            "text": "Manjaro",
            "link": "/os/manjaro/"
          },
          {
            "text": "Ubuntu",
            "link": "/os/ubuntu/"
          },
          {
            "text": "CentOS",
            "link": "/os/centos/"
          }
        ]
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "JavaScript",
            "link": "/frontend/javascript/"
          },
          {
            "text": "CSS",
            "link": "/frontend/css/"
          },
          {
            "text": "Webpack",
            "link": "/frontend/webpack/"
          },
          {
            "text": "D3",
            "link": "/frontend/d3js/"
          },
          {
            "text": "Utils",
            "link": "/frontend/utils/"
          }
        ]
      },
      {
        "text": "后端",
        "items": [
          {
            "text": "Nodejs",
            "link": "/backend/nodejs/"
          },
          {
            "text": "Koa",
            "link": "/backend/koa/"
          },
          {
            "text": "MongoDB",
            "link": "/backend/mongodb/"
          },
          {
            "text": "Nginx",
            "link": "/backend/nginx/"
          }
        ]
      },
      {
        "text": "开发工具",
        "items": [
          {
            "text": "Git",
            "link": "/tools/git/"
          },
          {
            "text": "Github",
            "link": "/tools/github/"
          },
          {
            "text": "VSCode",
            "link": "/tools/vscode/"
          },
          {
            "text": "Chrome Developer tools",
            "link": "/tools/chrome/"
          },
          {
            "text": "Bookmark scripts",
            "link": "/tools/bookmark-scripts/"
          }
        ]
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "面试题",
            "link": "/more/interview/"
          },
          {
            "text": "小工具",
            "link": "/more/hodgepodge/"
          },
          {
            "text": "VuePress1.x 官网",
            "link": "https://v1.vuepress.vuejs.org/zh/"
          }
        ]
      }
    ],
    "sidebar": {
      "/computer/": [
        "data-write",
        "how-networks-work"
      ],
      "/guide/": [
        "about-me",
        "docs-style"
      ]
    },
    "algolia": {
      "appId": "M698VCXCJN",
      "apiKey": "8b552055fb68ffc808bfbd3f98a1dbe2",
      "indexName": "shanyuhai_documents",
      "algoliaOptions": {
        "hitsPerPage": 10,
        "facetFilters": ""
      }
    }
  }
}