/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "百香果的前端进阶",
  "description": "百香果的文档, vuepress 文档",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/apple-touch-icon.png"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#ffffff"
      }
    ],
    [
      "meta",
      {
        "name": "google-site-verification",
        "content": "Ld_AEWr30siza2LmmZ12csitRGsSj9gqqEAch0UXkTc"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "百香果的前端进阶",
        "tagline": "文档, 博客",
        "actionText": "进入笔记 →",
        "actionLink": "/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4ea1e318",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "关于~~文档~~笔记",
          "slug": "关于文档笔记"
        }
      ],
      "lastUpdated": "2020年7月19日星期日下午12点49分"
    }
  ],
  "themeConfig": {
    "lastUpdated": "上次更新",
    "repo": "TTTurbo/documents",
    "editLinks": true,
    "editLinkText": "编辑文档！",
    "docsDir": "docs",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "先导",
        "link": "/guide/"
      },
      {
        "text": "计算机",
        "link": "/computer/"
      },
      {
        "text": "系统",
        "items": [
          {
            "text": "Linux",
            "link": "/os/linux/"
          },
          {
            "text": "Manjaro",
            "link": "/os/manjaro/"
          },
          {
            "text": "Ubuntu",
            "link": "/os/ubuntu/"
          },
          {
            "text": "CentOS",
            "link": "/os/centos/"
          }
        ]
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "JavaScript",
            "link": "/frontend/javascript/"
          },
          {
            "text": "CSS",
            "link": "/frontend/css/"
          },
          {
            "text": "Webpack",
            "link": "/frontend/webpack/"
          },
          {
            "text": "D3",
            "link": "/frontend/d3js/"
          },
          {
            "text": "Utils",
            "link": "/frontend/utils/"
          }
        ]
      },
      {
        "text": "后端",
        "items": [
          {
            "text": "Nodejs",
            "link": "/backend/nodejs/"
          },
          {
            "text": "Koa",
            "link": "/backend/koa/"
          },
          {
            "text": "MongoDB",
            "link": "/backend/mongodb/"
          },
          {
            "text": "Nginx",
            "link": "/backend/nginx/"
          }
        ]
      },
      {
        "text": "开发工具",
        "items": [
          {
            "text": "Git",
            "link": "/tools/git/"
          },
          {
            "text": "Github",
            "link": "/tools/github/"
          },
          {
            "text": "VSCode",
            "link": "/tools/vscode/"
          },
          {
            "text": "Chrome Developer tools",
            "link": "/tools/chrome/"
          },
          {
            "text": "Bookmark scripts",
            "link": "/tools/bookmark-scripts/"
          }
        ]
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "面试题",
            "link": "/more/interview/"
          },
          {
            "text": "小工具",
            "link": "/more/hodgepodge/"
          },
          {
            "text": "VuePress1.x 官网",
            "link": "https://v1.vuepress.vuejs.org/zh/"
          }
        ]
      }
    ],
    "algolia": {
      "appId": "M698VCXCJN",
      "apiKey": "8b552055fb68ffc808bfbd3f98a1dbe2",
      "indexName": "shanyuhai_documents",
      "algoliaOptions": {
        "hitsPerPage": 10,
        "facetFilters": ""
      }
    }
  }
}